apiVersion: v1
kind: Secret
metadata:
  name: regcred
  labels:
    app: oauth2-proxy
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyAiYXV0aHMiOiB7ICJpbnRlY2h3dy1kb2NrZXItbG9jYWwuamZyb2cuaW8iOiB7ICJhdXRoIjogImRHVmhiWEJzWVhrNlFWQXpUV1V6TlZoSFZITkJaWE0wTjJaQlJVWnRja1ozVEZWdGVUSjJjMjVXY1VWeGNtYz0iIH0gfSB9
